"""Diagnostics and suggestions for configuring the package.

It returns DATA, not text: the caller decides whether to render for a person, as JSON
or for an agent. That is what lets the same diagnostic serve a terminal wizard and a
tool called by another program.

Every check carries its FIX with it. A diagnostic that says "failed" without saying
what to do forces the reader to go hunting through documentation, and that is where
people give up.
"""
from dataclasses import dataclass, asdict

from .config import Config, ConfigError
from .embedding import Embedder
from .errors import CoreError
from .reranking import Reranker

#: Prefixes of collections generated by another system — not useful candidates.
NOISE_PREFIXES = ("ws-",)

#: How the host spells its command line, prefixed onto the fixes this module suggests.
#:
#: The core is not supposed to know the host exists — that is the whole portability
#: claim, and `grep -ri claude core/` is clean. But the diagnostics were emitting
#: "qctx config set …" as the fix for a missing setting, which is this CLI's spelling and
#: nobody else's: ported to another host, the diagnostic would tell the user to run a
#: command that does not exist there. An adapter overrides this; it is not a hard-coded
#: name any more, which is the part that mattered.
COMMAND_PREFIX = "qctx"


@dataclass
class Check:
    name: str
    ok: bool
    detail: str
    fix_hint: str | None = None
    warning: bool = False  # a failure that degrades rather than blocks


def _check_qdrant(cfg: Config) -> tuple[Check, object]:
    if not cfg.qdrant_url:
        return Check("Qdrant", False, "qdrant_url is not configured",
                     "export QCTX_QDRANT_URL=https://your-qdrant"), None
    from .qdrant import Qdrant, QdrantError
    q = Qdrant(cfg.qdrant_url, cfg.qdrant_api_key, timeout=10.0)
    try:
        names = q.list_collections()
    except QdrantError as exc:
        hint = "check QCTX_QDRANT_API_KEY" if "401" in str(exc) or "403" in str(exc) \
            else "check the URL and whether the service is up"
        return Check("Qdrant", False, f"did not answer: {exc}", hint), None

    return Check("Qdrant", True, f"{len(names)} collections at {cfg.qdrant_url}"), q


def _check_embed(cfg: Config) -> tuple[Check, int | None]:
    try:
        url = cfg.resolved_embed_url()
    except ConfigError as exc:
        return Check("Embedding", False, str(exc),
                     "export QCTX_EMBED_URL=… or QCTX_API_BASE_URL=…"), None
    emb = Embedder(url, cfg.embed_model, cfg.api_key, timeout=30.0)
    try:
        dim = emb.detect_dimension()
    except CoreError as exc:
        return Check("Embedding", False, f"{url} did not answer: {exc}",
                     f"check whether the model {cfg.embed_model!r} is served at that address"), None
    detail = f"{cfg.embed_model} returns {dim} dimensions"
    if dim != cfg.vector_size:
        return Check("Embedding", False,
                     f"{detail}, but vector_size is {cfg.vector_size}",
                     f"{COMMAND_PREFIX} config detect"), dim

    return Check("Embedding", True, detail), dim


def _check_rerank(cfg: Config) -> Check:
    """Re-ranking is optional: without it search works, it just orders worse. A failure
    here is a WARNING, never a blocker — treating it as an error would make someone
    without a reranker conclude the package is useless."""
    try:
        url = cfg.resolved_rerank_url()
    except ConfigError:
        return Check("Re-rank", False, "not configured (optional)",
                     "export QCTX_RERANK_URL=… to gain precision in search", warning=True)
    rr = Reranker(url, cfg.rerank_model, cfg.api_key, timeout=20.0)
    pairs, info = rr.rank(
        "what is the capital of France?",
        ["Paris is the capital of France.", "carrot cake recipe with frosting"],
    )
    if not info["ok"]:
        return Check("Re-rank", False, f"{url} failed: {info['error']}",
                     f"check whether the server came up with rerank support and whether the "
                     f"model {cfg.rerank_model!r} is there", warning=True)
    scale = "raw logit (normalized to sigmoid)" if info["was_logit"] else "sigmoid 0..1"
    best = max(s for _, s in pairs)
    top_is_right = pairs[0][0] == 0
    detail = (f"{cfg.rerank_model} answers in {scale} via the {info['contract']} "
              f"contract; best score {best:.3f}")
    if not top_is_right:
        return Check("Re-rank", False,
                     f"{detail} — but it ranked the WRONG answer first",
                     "the model may not be a rerank cross-encoder", warning=True)

    return Check("Re-rank", True, detail)


def _check_collections(cfg: Config, q) -> list[Check]:
    checks = []
    # ALL FIVE, and the count is the point. `Config._require_distinct` enumerates five; this
    # enumerated three, so `setup` reported "ready" on a configuration where the repository
    # archive sat on top of the memory collection — a collision whose first consequence, in
    # that guard's own words, is code chunks drowning the curated archive. The guard did
    # fire, but only once a repos command ran, which is long after the diagnostic was
    # believed. A diagnostic that omits a role cannot report anything about it.
    #
    # THE REGISTRY IS THE ONE WHOSE DIMENSION IS NOT THE MODEL'S. It stores no meaning in
    # its vector — `core/repos.py` sizes it 1 and says why — so checking it against
    # `vector_size` would report a correct install as broken, which is the same lie in the
    # other direction. Each role therefore carries the dimension it actually expects.
    from .repos import REGISTRY_VECTOR_SIZE

    roles = (
        ("memory_collection", cfg.memory_collection, "memory-collection", True,
         cfg.vector_size),
        ("docs_collection", cfg.docs_collection, "docs-collection", False,
         cfg.vector_size),
        ("library_collection", cfg.library_collection, "library-collection", False,
         cfg.vector_size),
        ("repos_collection", cfg.repos_collection, "repos-collection", False,
         cfg.vector_size),
        ("repos_registry_collection", cfg.repos_registry_collection,
         "repos-registry-collection", False, REGISTRY_VECTOR_SIZE),
    )
    seen_values: dict[str, str] = {}
    for field, value, cli_key, required, expected_dim in roles:
        if not value:
            checks.append(Check(field, not required,
                                "not configured",
                                f"{COMMAND_PREFIX} config set {cli_key} <name>",
                                warning=not required))
            continue
        if value in seen_values:
            checks.append(Check(field, False,
                                f"{value!r} is already used by {seen_values[value]}",
                                f"{COMMAND_PREFIX} config set {cli_key} <another-name> — each role has "
                                f"a different lifecycle and needs its own collection"))
            continue
        seen_values[value] = field
        if q is None:
            checks.append(Check(field, True, f"{value!r} (Qdrant unreachable, not verified)"))
            continue
        info = q.collection_info(value)
        if info is None:
            checks.append(Check(field, True, f"{value!r} will be created on first use"))
            continue
        dim = info.get("size")
        if dim not in (None, expected_dim):
            checks.append(Check(field, False,
                                f"{value!r} has dimension {dim}, this role uses {expected_dim}",
                                "pick another collection or another embedding model"))
            continue
        checks.append(Check(field, True, f"{value!r} — {info.get('points')} points"))

    return checks


def suggest_collections(q, vector_size: int, cutoff: int = 8) -> list[dict]:
    """Existing collections usable as a memory archive, best first.

    It sorts by point count because an already populated archive is the obvious
    candidate, and it hides the ones generated by another system, which are noise for
    this choice.
    """
    if q is None:
        return []
    output = []
    for name in q.list_collections():
        if name.startswith(NOISE_PREFIXES):
            continue
        info = q.collection_info(name) or {}
        if info.get("size") not in (None, vector_size):
            continue
        output.append({"collection": name, "points": info.get("points") or 0})
    output.sort(key=lambda c: -c["points"])

    return output[:cutoff]


def diagnose(cfg: Config) -> dict:
    """Runs every check and returns the full picture."""
    check_q, q = _check_qdrant(cfg)
    check_emb, dim = _check_embed(cfg)
    checks = [check_q, check_emb, _check_rerank(cfg)]
    checks += _check_collections(cfg, q)

    blockers = [c for c in checks if not c.ok and not c.warning]
    warnings = [c for c in checks if not c.ok and c.warning]

    return {
        "ready": not blockers,
        "checks": [asdict(c) for c in checks],
        "blockers": [asdict(c) for c in blockers],
        "warnings": [asdict(c) for c in warnings],
        "detected_dim": dim,
        "memory_suggestions": suggest_collections(q, cfg.vector_size),
    }


def choose_by_index(options: list[str], entry: str) -> str | None:
    """Resolves the user's choice: a number from the list, or a typed name.

    Separated from terminal reading on purpose — it is the only part of the wizard with
    any logic, so it is the only one that needs a test. Returns None when the input
    selects nothing (empty = keep the current value).
    """
    entry = (entry or "").strip()
    if not entry:
        return None
    if entry.isdigit():
        ix = int(entry) - 1
        if 0 <= ix < len(options):
            return options[ix]

        return None

    return entry
